# -------------------------------------
# (1) 공통 설정 (기본 프로필)
# -------------------------------------
server:
  port: 8888

spring:
  application:
    name: config-server

---
# -------------------------------------
# (2) 'local' 프로필: 로컬에서 실행할 때 사용
# -------------------------------------
spring:
  config:
    activate:
      on-profile: "local" # 이 설정은 'local' 프로필일 때만 활성화됩니다.
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Song-min-geun/stockproject-config.git
          default-label: main
          username: Song-min-geun
          # 로컬에서는 터미널에 export로 설정한 GIT_TOKEN 값을 사용합니다.
          password: ${GIT_TOKEN}

---
# -------------------------------------
# (3) 'docker' 프로필: EC2에 배포할 때 사용
# -------------------------------------
spring:
  config:
    activate:
      on-profile: "docker" # 이 설정은 'docker' 프로필일 때만 활성화됩니다.
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Song-min-geun/stockproject-config.git
          default-label: main
          username: Song-min-geun
          # 배포 시에는 GitHub Secrets에 저장된 GIT_TOKEN 값을 주입받습니다.
          password: ${GIT_TOKEN}